common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "common"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="common/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from repybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pybo/", include("repybo.urls")),
    path("common/", include("common.urls")),
    path("", base_views.index, name="index"),
]

repybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = "pybo"

urlpatterns = [
    # base_views
    path("", base_views.index, name="index"),
    path("<int:question_id>/", base_views.detail, name="detail"),

    # question_views
    path("question/create/", question_views.question_create, name="question_create"),
    path("question/modify/<int:question_id>/", question_views.question_modify, name="question_modify"),
    path("question/delete/<int:question_id>/", question_views.question_delete, name="question_delete"),
    path("question/vote/<int:question_id>/", question_views.question_vote, name="question_vote"),
    path("question/cancel_vote/<int:question_id>/", question_views.question_cancel_vote, name="question_cancel_vote"),

    # answer_views
    path("answer/create/<int:question_id>/", answer_views.answer_create, name="answer_create"),
    path("answer/modify/<int:answer_id>/", answer_views.answer_modify, name="answer_modify"),
    path("answer/delete/<int:answer_id>/", answer_views.answer_delete, name="answer_delete"),
    path("answer/vote/<int:answer_id>/", answer_views.answer_vote, name="answer_vote"),
    path("answer/cancel_vote/<int:answer_id>/", answer_views.answer_cancel_vote, name="answer_cancel_vote"),

    ### generic view 연습
    # path("", views.IndexView.as_view()),
    # path("<int:pk>/", views.DetailView.as_view()),
]

repybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    
    subject = models.CharField(max_length=200)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="question_author")
    
    content = models.TextField()

    voter = models.ManyToManyField(User, related_name="question_voter")

    views = models.IntegerField(default=0)

    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

    
    def __str__(self):
        return f"{self.id}({self.subject})"
    
    
class Answer(models.Model):
    
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="answer_author")
    
    content = models.TextField(default=0)

    voter = models.ManyToManyField(User, related_name="answer_voter")

    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Answer_{self.id} of Question_{self.question.id}('{self.question.subject}')"

repybo/forms.py
from django import forms

from .models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["subject", "content"]

        labels = {"subject": "제목",
                 "content": "질문 내용"}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]

        labels = {"content": "답변 내용"}

repybo/views/answer_views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Question, Answer
from ..forms import AnswerForm

@login_required(login_url="common:login")
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            # return redirect("pybo:detail", question_id=question.id)
            return redirect(f"{resolve_url('pybo:detail', question_id=answer.question.id)}#answer_{answer.id}")
    else:
        form = AnswerForm()

    context = {"question": question, "form": form}
    return render(request, "repybo/question_detail.html", context)



@login_required(login_url="common:login")
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    question_id = answer.question.id

    if request.user != answer.author:
        messages.error(request, "답변 수정 권한이 없습니다.")
        return redirect("pybo:detail", question_id)

    if request.method=="POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save()
            # return redirect("pybo:detail", question_id)
            return redirect(f"{resolve_url('pybo:detail', question_id=answer.question.id)}#answer_{answer.id}")
    else:
        form = AnswerForm(instance=answer)

    context={"question":answer.question, "answer":answer, "form":form}
    return render(request, "repybo/question_detail.html", context)
    # return redirect(f"{resolve_url('pybo:detail', question_id=answer.question.id)}#answer_{answer.id}")


@login_required(login_url="common:login")
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user != answer.author:
        messages.error(request, "삭제 권한이 없습니다.")
        return redirect("pybo:detail", answer.question.id)

    answer.delete()
    return redirect("pybo:detail", answer.question.id)


@login_required(login_url="common:login")
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user == answer.author:
        messages.error(request, "자신의 글은 추천할 수 없습니다.")
    else:
        answer.voter.add(request.user)

    # return redirect("pybo:detail", question_id=answer.question.id)
    return redirect(f"{resolve_url('pybo:detail', question_id=answer.question.id)}#answer_{answer.id}")


def answer_cancel_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.user in answer.voter.all():
        answer.voter.remove(request.user)

    return redirect("pybo:detail", question_id=answer.question.id)

repybo/views/base_views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q

from ..models import Question


def index(request):
    page = request.GET.get("page", "1")
    kw = request.GET.get("kw", '')

    question_list = Question.objects.order_by("-create_date")

    if kw:
        question_list = question_list.filter(Q(subject__icontains=kw)|Q(content__icontains=kw)|
                                             Q(author__username__icontains=kw)|Q(answer__content__icontains=kw)|
                                             Q(answer__author__username__icontains=kw)).distinct()

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {"question_list": page_obj, "page": page, "kw": kw}
    return render(request, "repybo/question_list.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    cname_vst_q = "ck_vst"
    cval_vst_q = request.COOKIES.get(cname_vst_q, '')
    if request.user == question.author:  # 현재 사용자가 질문 작성자일 때 skip
        pass
    else:
        # Cookie 생성
        ### 익명 사용자 방문 이력 cookie 가 존재하지 않을 때
        if len(request.user.username) == 0 and cval_vst_q[:7] != "visited":
            cval_vst_q = f"visited: "

        ### 현재 사용자의 cookie 가 존재하지 않을 때
        elif not (cval_vst_q and cval_vst_q.__contains__(request.user.username)):
            cval_vst_q = f"{request.user.username}_visited: "

        # 방문 이력이 없을 때 조회수 증가
        if not cval_vst_q.__contains__(f"{question_id},"):
            cval_vst_q += f"{question_id},"
            question.views += 1

    question.save()
    context = {"question": question}
    response = render(request, "repybo/question_detail.html", context)

    if cval_vst_q:
        response.set_cookie(cname_vst_q, cval_vst_q)

    return response


######## generic view 연습
# from django.views import generic
#
# class IndexView(generic.ListView):
#     def get_queryset(self):
#         return Question.objects.order_by("-create_date")
#
# class DetailView(generic.DetailView):
#     model = Question

repybo/views/question_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Question
from ..forms import QuestionForm

@login_required(login_url="common:login")
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            return redirect("pybo:index")
    else:
        form = QuestionForm()

    context = {"form": form}
    return render(request, "repybo/question_form.html", context)

@login_required(login_url="common:login")
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "질문 수정 권한이 없습니다.")
        return redirect("pybo:detail", question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect("pybo:detail", question_id=question.id)
    else:
        form = QuestionForm(instance=question)

    context = {"form": form}
    return render(request, "repybo/question_form.html", context)


@login_required(login_url="common:login")
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.user != question.author:
        messages.error(request, "삭제 권한이 없습니다.")
        return redirect("pybo:detail", question.id)

    question.delete()
    return redirect("pybo:index")


@login_required(login_url="common:login")
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.user == question.author:
        messages.error(request, "자신의 글은 추천할 수 없습니다.")
    else:
        question.voter.add(request.user)

    return redirect("pybo:detail", question_id=question.id)


def question_cancel_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.user in question.voter.all():
        question.voter.remove(request.user)

    return redirect("pybo:detail", question_id=question.id)

templates/repybo/answer_form.html
{% extends 'repybo/question_detail.html' %}

{% block answer_form %}
    <form method="post">
        {% csrf_token %}
        {%  include 'form_errors.html' %} <!-- 오류 표시 -->
        <div class="mb-3">
            <label for="content" class="form-label">답변 내용</label>
            <textarea name="content" id="content" rows="10" class="form-control" {% if not user.is_authenticated %}disabled{% endif %}>{{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
{% endblock %}

templates/repybo/question_detail.html
{%  extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
    <div class="container my-3">
        {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for msg in messages %}
                <strong>{{ msg.tags }}</strong>
                <ul><li>{{ msg.message }}</li></ul>
            {%  endfor %}
        </div>
        {% endif %}
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text">{{ question.content|mark }}</div>
                    <div class="d-flex justify-content-end mb-3">조회수 {{ question.views }}</div>
                <div class="d-flex justify-content-end">
                    <div class="badge bg-light text-dark p-2 text-start mx-2">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                    <div class="badge bg-light text-dark p-2 text-start">
                        <div class="mb-2">{{ question.author.username }}</div>
                        <div>{{ question.create_date }}</div>
                    </div>
                </div>
                <div class="my-3">
                    {% if not request.user in question.voter.all %}
                    <a href="javascript:void(0)" class="recommend btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_vote' question.id %}" data-voter="{{ question.voter }}">
                        추천
                    {%  else %}
                    <a href="javascript:void(0)" class="cancel_recommend btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_cancel_vote' question.id %}" data-voter="{{ question.voter }}">
                        추천 취소
                    {% endif %}
                        <span class="badge rounded-pill bg-success">{{ question.voter.count }}</span>
                    </a>

                    {% if request.user == question.author %}
                    <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="javascript:void(0)" class="btn btn-sm btn-outline-secondary delete" data-uri="{% url 'pybo:question_delete' question.id%}">삭제</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }} 개의 답변이 있습니다.</h5>
        {% for a_from_q in question.answer_set.all %}
            <a id="answer_{{ a_from_q.id }}"></a>
            {% if a_from_q.id == answer.id %}
{#                {% block answer_form %}#}
{#                {% endblock %}#}
            <form method="post">
                {% csrf_token %}
                {%  include 'form_errors.html' %} <!-- 오류 표시 -->
                <div class="mb-3">
                    <label for="content" class="form-label">답변 내용</label>
                    <textarea name="content" id="content" rows="10" class="form-control"
                              {% if not user.is_authenticated %}disabled{% endif %}>{{ form.content.value|default_if_none:'' }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary mb-5">저장하기</button>
            </form>
            {% else %}
            <div class="card my-3">
                <div class="card-body">
                    <div class="card-text">{{ a_from_q.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge bg-light text-dark p-2 text-start mx-2">
                            <div class="mb-2">modified at</div>
                            <div>{{ a_from_q.modify_date }}</div>
                        </div>
                        <div class="badge bg-light text-dark p-2 text-start">
                            <div class="mb-2">{{ a_from_q.author.username }}</div>
                            <div>{{ a_from_q.create_date }}</div>
                        </div>
                    </div>
                    <div class="my-3">
                        {% if not request.user in a_from_q.voter.all %}
                        <a href="javascript:void(0)" class="recommend btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_vote' a_from_q.id %}">
                            추천
                        {%  else %}
                        <a href="javascript:void(0)" class="cancel_recommend btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_cancel_vote' a_from_q.id %}">
                            추천 취소
                        {% endif %}
                            <span class="badge rounded-pill bg-success">{{ a_from_q.voter.count }}</span>
                        </a>
                        {% if request.user == a_from_q.author %}
                        <a href="{% url 'pybo:answer_modify' a_from_q.id %}#answer_{{ a_from_q.id }}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="javascript:void(0)" class="btn btn-sm btn-outline-secondary delete" data-uri="{% url 'pybo:answer_delete' a_from_q.id%}">삭제</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
        {%  endfor %}

        <form action="{%  url 'pybo:answer_create' question.id %}" method="post">
        {%  csrf_token %}
        {%  include 'form_errors.html' %} <!-- 오류 표시 -->
        <div class="mb-3">
            <label for="content" class="form-label">답변 내용</label>
            <textarea name="content" id="content" rows="10" class="form-control" {% if not user.is_authenticated %}disabled{% endif %}></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

{% block script %}
<script type="text/javascript">
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function (element) {
    element.addEventListener("click", function () {
        if (confirm("정말 삭제하시겠습니까?")){
            location.href = this.dataset.uri;
        };
    });
});

const vote_elements = document.getElementsByClassName("recommend");
Array.from(vote_elements).forEach(function(element){
    element.addEventListener("click", function(){
       if (confirm("정말 추천하시겠습니까?")){
           location.href = this.dataset.uri;
       };
    });
});


const cancel_vote_elements = document.getElementsByClassName("cancel_recommend");
Array.from(cancel_vote_elements).forEach(function(element){
    element.addEventListener("click", function(){
       if (confirm("정말 추천을 취소하시겠습니까?")){
           location.href = this.dataset.uri;
       };
    });
});


</script>
{% endblock %}

templates/repybo/question_form.html
{%  extends 'base.html' %}
{% block content %}
    <div class="container">
        <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
        <form method="post">
            {% csrf_token %}
            {%  include 'form_errors.html' %} <!-- 오류 표시 -->
            <div class="my-3">
                <label for="subject" class="form-label">제목</label>
                <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
            </div>
            <div class="my-3">
                <label for="content" class="form-label">내용</label>
                <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

templates/repybo/question_list.html
{%  extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a class="btn btn-primary " href="{%  url 'pybo:question_create' %}">질문 등록</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input class="form-control" type="text" id="search_kw" name="search_kw" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search" name="btn_search">검색</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="table-dark text-center">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>작성자</th>
            <th>작성일시</th>
            <th>조회수</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for q in question_list %}
                <tr class="text-center">
                    <td>{{ question_list.paginator.count | sub:question_list.start_index | sub:forloop.counter0|add:1 }}</td>
                    <td class="text-start">
                        <a href="{% url 'pybo:detail' q.id %}">{{ q.subject }}</a>
                        {% if q.answer_set.count > 0 %}
                            <span class="text-danger small mx-2">{{ q.answer_set.count }}</span>
                        {% endif %}
                    </td>
                    <td>{{ q.author.username }}</td>
                    <td>{{ q.create_date }}</td>
                    <td>{{ q.views }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <td colspan="4">질문이 없습니다.</td>
        {%  endif %}
        </tbody>
    </table>
    <!-- 페이징 시작 -->
    <ul class="pagination justify-content-center">

        <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
            <!-- 첫 페이지 -->
            <li class="page-item"><a class="page-link" href="javascript:void(0)" data-page="{{ question_list.paginator.page_range.start }}"><<</a></li>
            <li class="page-item"><a class="page-link" href="javascript:void(0)" data-page="{{ question_list.previous_page_number }}"><</a></li>
        {% endif %}

        <!-- 페이지 목록 -->
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                {% if page_number == question_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="javascript:void(0)" data-page="{{ page_number }}">{{ page_number }}</a> <!-- 게시물 수 증가를 실시간으로 반영하게 하려면 현재 페이지 버튼이 활성화 되어 있어야 함. -->
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0)" data-page="{{ page_number }}">{{ page_number }}</a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
            <li class="page-item"><a class="page-link" href="javascript:void(0)" data-page="{{ question_list.next_page_number }}">></a></li>
            <!-- 끝 페이지 -->
            <li class="page-item"><a class="page-link" href="javascript:void(0)" data-page="{{ question_list.paginator.num_pages }}">>></a></li>
        {% endif %}
    </ul>
</div>
<form method="get" id="searchForm" action="{% url 'pybo:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page|default_if_none:1 }}">
</form>
{% endblock %}

{% block script %}
<script type="text/javascript">
{# Page 번호 버튼 눌렸을 때  #}
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element){
    element.addEventListener("click", function(){
       document.getElementById("page").value = this.dataset.page;
       document.getElementById("searchForm").submit();
    });
});
{# '검색' 버튼을 눌렀을 때  #}
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener("click", function(){
   document.getElementById("kw").value = document.getElementById("search_kw").value;
   document.getElementById("page").value = 1;
   document.getElementById("searchForm").submit();
});
</script>
{% endblock %}