common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "common"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="common/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from repybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("pybo/", include("repybo.urls")),
    path("common/", include("common.urls")),
    path("", base_views.index, name="index"),
]

repybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = "pybo"

urlpatterns = [
    # base_views
    path("", base_views.index, name="index"),
    path("<int:question_id>/", base_views.detail, name="detail"),

    # question_views
    path("question/create/", question_views.question_create, name="question_create"),
    path("question/modify/<int:question_id>/", question_views.question_modify, name="question_modify"),
    path("question/delete/<int:question_id>/", question_views.question_delete, name="question_delete"),
    path("question/vote/<int:question_id>/", question_views.question_vote, name="question_vote"),
    path("question/cancel_vote/<int:question_id>/", question_views.question_cancel_vote, name="question_cancel_vote"),

    # answer_views
    path("answer/create/<int:question_id>/", answer_views.answer_create, name="answer_create"),
    path("answer/modify/<int:answer_id>/", answer_views.answer_modify, name="answer_modify"),
    path("answer/delete/<int:answer_id>/", answer_views.answer_delete, name="answer_delete"),
    path("answer/vote/<int:answer_id>/", answer_views.answer_vote, name="answer_vote"),
    path("answer/cancel_vote/<int:answer_id>/", answer_views.answer_cancel_vote, name="answer_cancel_vote"),

    ### generic view 연습
    # path("", views.IndexView.as_view()),
    # path("<int:pk>/", views.DetailView.as_view()),
]

repybo/views/base_views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q

from ..models import Question


def index(request):
    page = request.GET.get("page", "1")
    kw = request.GET.get("kw", '')

    question_list = Question.objects.order_by("-create_date")

    if kw:
        question_list = question_list.filter(Q(subject__icontains=kw)|Q(content__icontains=kw)|
                                             Q(author__username__icontains=kw)|Q(answer__content__icontains=kw)|
                                             Q(answer__author__username__icontains=kw)).distinct()

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {"question_list": page_obj, "page": page, "kw": kw}
    return render(request, "repybo/question_list.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    cname_vst_q = "ck_vst"
    cval_vst_q = request.COOKIES.get(cname_vst_q, '')
    if request.user == question.author:  # 현재 사용자가 질문 작성자일 때 skip
        pass
    else:
        # Cookie 생성
        ### 익명 사용자 방문 이력 cookie 가 존재하지 않을 때
        if len(request.user.username) == 0 and cval_vst_q[:7] != "visited":
            cval_vst_q = f"visited: "

        ### 현재 사용자의 cookie 가 존재하지 않을 때
        elif not (cval_vst_q and cval_vst_q.__contains__(request.user.username)):
            cval_vst_q = f"{request.user.username}_visited: "

        # 방문 이력이 없을 때 조회수 증가
        if not cval_vst_q.__contains__(f"{question_id},"):
            cval_vst_q += f"{question_id},"
            question.views += 1

    question.save()
    context = {"question": question}
    response = render(request, "repybo/question_detail.html", context)

    if cval_vst_q:
        response.set_cookie(cname_vst_q, cval_vst_q)

    return response


######## generic view 연습
# from django.views import generic
#
# class IndexView(generic.ListView):
#     def get_queryset(self):
#         return Question.objects.order_by("-create_date")
#
# class DetailView(generic.DetailView):
#     model = Question

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <title>Pybo</title>
</head>
<body>
<!-- 네비게이션 바 -->
{% include "navbar.html" %}
{% block content %}
{%  endblock %}
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    <div class="alert alert-danger">
        {% for field in form %}
        {% if field.errors %}
        <div>
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
        </div>
        {% endif %}
        {% endfor %}

        {% for nferror in form.non_field_errors %}
        <div>
            <strong>{{ nferror }}</strong>
        </div>
        {% endfor %}
    </div>
{% endif %}

templates/navbar.html
<div class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {%  if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">로그아웃({{ user.username }})</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>

                <li class="nav-item">
                    {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:signup' %}">회원 가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</div>